//Generated by xtext. Generator by olnor18
package math_expression;
public class Test27 {
	
	private External external;
	
	public Test27(External external) {
		this.external = external;
	}
	
	public void compute() {
		x = pi();
		y = x + 2;
	}

	interface External {
		public int pi();
	}
}
