//Generated by xtext. Generator by olnor18
package math_expression;
public class Test34 {
	
	private External external;
	
	public Test34(External external) {
		this.external = external;
	}
	
	public void compute() {
		sideA = 3;
		sideB = 4;
		sideC = sqrt(pow(sideA, 2) + pow(sideB, 2));
		perimeterTriangle = sideA + sideB + sideC;
		radius = 5;
		perimeterCircle = 2 * radius * pi();
	}

	interface External {
		public int pow(int n, int m);
		public int sqrt(int n);
		public int pi();
	}
}
