//Generated by xtext. Generator by olnor18
package math_expression;
public class Test32 {
	
	
	public void compute() {
		a = 40;
		b = 40 + 2;
		c = 40 + 5 - 10 - 8;
		d = 40 + 2 * 4 + 80;
		e = (40 + 2) * (4 + 80);
	}

}
