//Generated by xtext. Generator by olnor18
package math_expression;
public class Test31 {
	
	private External external;
	
	public Test31(External external) {
		this.external = external;
	}
	
	public void compute() {
		x = 5;
		y = 2 + pow(x - 3, 3 * 2);
	}

	interface External {
		public int pow(int n, int m);
	}
}
