/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.validation

import dk.sdu.mmmi.mdsd.math.*
import org.eclipse.xtext.validation.Check
import dk.sdu.mmmi.mdsd.math.MathPackage
import org.eclipse.xtext.EcoreUtil2

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathValidator extends AbstractMathValidator {
	
	public static val DUPLICATE_NAME = 'duplicateName'
	public static val INVALID_PARAMETERS = 'invalidParameters'
	
	@Check
	def cannotReasignGlobalVar(MathExp mathexp) {
		val root = EcoreUtil2.getContainerOfType(mathexp, Math)
		if(root.lines.filter[it !== mathexp && it.value.name == mathexp.value.name].size > 0) {
			error('Cannot assign global variable with same name', 
					MathPackage.Literals.MATH_EXP__VALUE,
					DUPLICATE_NAME)
		}
	}
	
		@Check
	def checkParameters(ExternalUse externalUse) {
		if (externalUse.ref.argsType.size !== externalUse.parameters.size) {
			error('The parameters does not match the defined external', 
					MathPackage.Literals.EXTERNAL_USE__PARAMETERS,
					INVALID_PARAMETERS)
		}
	}
	
}
